---
- name: install java
  hosts: all
  gather_facts: false
  tasks:
    - name: update repos
      yum:
        name: "*"
        state: latest
    - name: instling openJK
      yum:
        name: java:1.8.0-openjdk
    - name: setting default java
      alternatives:
        name: java
        link: /usr/bin/java
        path: /usr/lib/jvm/jre-1.8.0-openjdk.x86_64/bin/java
    - name: download tomcat
      get_url:
        url: "https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.65/bin/apache-tomcat-9.0.65.tar.gz"
        dest: /usr/local
    - name: extracting tomcat
      unarchive:
      src: "/usr/local/apache-tomcat-9.0.65.tar.gz"
      dest: /usr/local
      remote_src: yes
    - name: renmae tomcat
      command: mv /usr/local/apache-tomcat-9.0.65 /usr/local/tomcat
    - name: starting tomcat
      shell: nohup /usr/local/tomcat/bin/startup.sh &
